name: carzz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  iconify_flutter: ^0.0.4
  carousel_slider: ^4.1.1
  flutter_image_slideshow: ^0.1.4
  dio: ^4.0.6
  connectivity_plus: ^2.3.7


 
  
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

